### 신규 상품 등록
POST localhost:8080/api/items
Content-Type: application/json

{
  "name": "itemA",
  "price": 1000,
  "quantity": 3000,
  "description": "this is ItemA"
}

### 상품 입출고
POST localhost:8080/api/items/1/stock-update
Content-Type: application/json

{
  "stockTransactionType": "INCREASE",
  "quantity": 2000
}