name: Feature Branches Github Actions CI Test

on:
  push:
    branches:
      - feature/*

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Github Repository에 올린 파일들을 불러오기
      uses: actions/checkout@v4

    - name: JDK 17버전 설치
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: application.yml 파일 만들기
      run: echo "${{ secrets.APPLICATION_LOCAL_PROPERTY }}" > ./src/main/resources/application.yml

    - name: gradlew 실행 권한추가, 테스트 및 빌드하기
      run: |
        chmod +x ./gradlew
        ./gradlew clean build
